### ISSUE TITLE
Code for generating trajectories with A* algorithm

### ISSUE THREAD

**Issue by Shengqiang-Zhang** [whcpumpkin/Demand-driven-navigation#2]
I really like this demand-driven navigation work and think it's very interesting. 
I am very interested in generating trajectories with A* algorithms but could not find the code for this part. Do you plan to release the this code as well?
Thanks very much!

**Comment by whcpumpkin** [comment]
Hi!
Thank you for your interest in our work! In fact, we used code from [thortils](https://github.com/zkytony/thortils) (Thanks for their wonderful code).
We will release the trajectory-collection code soon.
